/** The gallery's menu group for a node, derived from its ancestry. */

// Ordered specific to general: the first entry found in [name, ...ancestors]
// decides the group.
const GROUP_RULES = [
  ['Light3D', 'Lighting'],
  ['ReflectionProbe', 'Reflection & global illumination'],
  ['VoxelGI', 'Reflection & global illumination'],
  ['LightmapGI', 'Reflection & global illumination'],
  ['LightmapProbe', 'Reflection & global illumination'],
  ['FogVolume', 'Reflection & global illumination'],
  ['Decal', 'Reflection & global illumination'],
  ['GPUParticlesCollision3D', 'Particles'],
  ['GPUParticlesAttractor3D', 'Particles'],
  ['GPUParticles3D', 'Particles'],
  ['CPUParticles3D', 'Particles'],
  ['Joint3D', 'Physics — joints'],
  ['VehicleWheel3D', 'Physics — vehicles'],
  ['SoftBody3D', 'Physics — bodies'],
  ['PhysicalBone3D', 'Physics — bodies'],
  ['PhysicsBody3D', 'Physics — bodies'],
  ['Area3D', 'Physics — areas'],
  ['CollisionObject3D', 'Physics — bodies'],
  ['CollisionShape3D', 'Collision shapes'],
  ['CollisionPolygon3D', 'Collision shapes'],
  ['RayCast3D', 'Physics — queries'],
  ['ShapeCast3D', 'Physics — queries'],
  ['SpringArm3D', 'Physics — queries'],
  ['NavigationRegion3D', 'Navigation'],
  ['NavigationLink3D', 'Navigation'],
  ['NavigationAgent3D', 'Navigation'],
  ['NavigationObstacle3D', 'Navigation'],
  ['Camera3D', 'Cameras'],
  ['AudioListener3D', 'Audio'],
  ['AudioStreamPlayer3D', 'Audio'],
  ['Skeleton3D', 'Skeleton, bones & IK'],
  ['BoneAttachment3D', 'Skeleton, bones & IK'],
  ['SkeletonModifier3D', 'Skeleton, bones & IK'],
  ['BoneConstraint3D', 'Skeleton, bones & IK'],
  ['Path3D', 'Paths & curves'],
  ['PathFollow3D', 'Paths & curves'],
  ['RemoteTransform3D', 'Transform helpers'],
  ['Marker3D', 'Markers & helpers'],
  ['GridMap', 'Tilemaps & grids'],
  ['CSGShape3D', 'CSG'],
  ['MultiMeshInstance3D', 'Meshes & rendering'],
  ['Label3D', 'Meshes & rendering'],
  ['SpriteBase3D', 'Meshes & rendering'],
  ['MeshInstance3D', 'Meshes & rendering'],
  ['GeometryInstance3D', 'Meshes & rendering'],
  ['VisibleOnScreenNotifier3D', 'Visibility'],
  ['VisibleOnScreenEnabler3D', 'Visibility'],
  ['XROrigin3D', 'XR / AR'],
  ['XRNode3D', 'XR / AR'],
  ['XRController3D', 'XR / AR'],
  ['XRAnchor3D', 'XR / AR'],
  ['OpenXRHand', 'XR / AR'],
  ['OpenXRCompositionLayer', 'XR / AR'],
  ['ImporterMeshInstance3D', 'Import / editor internals'],
  ['WorldEnvironment', 'Environment'],
  ['VisualInstance3D', 'Meshes & rendering'],

  ['Light2D', 'Lighting'],
  ['LightOccluder2D', 'Lighting'],
  ['Joint2D', 'Physics — joints'],
  ['PhysicsBody2D', 'Physics — bodies'],
  ['Area2D', 'Physics — areas'],
  ['CollisionObject2D', 'Physics — bodies'],
  ['CollisionShape2D', 'Collision shapes'],
  ['CollisionPolygon2D', 'Collision shapes'],
  ['RayCast2D', 'Physics — queries'],
  ['ShapeCast2D', 'Physics — queries'],
  ['GPUParticles2D', 'Particles'],
  ['CPUParticles2D', 'Particles'],
  ['NavigationRegion2D', 'Navigation'],
  ['NavigationLink2D', 'Navigation'],
  ['NavigationAgent2D', 'Navigation'],
  ['NavigationObstacle2D', 'Navigation'],
  ['Camera2D', 'Cameras'],
  ['AudioListener2D', 'Audio'],
  ['AudioStreamPlayer2D', 'Audio'],
  ['Skeleton2D', 'Skeleton, bones & IK'],
  ['Bone2D', 'Skeleton, bones & IK'],
  ['Path2D', 'Paths & curves'],
  ['PathFollow2D', 'Paths & curves'],
  ['RemoteTransform2D', 'Transform helpers'],
  ['Marker2D', 'Markers & helpers'],
  ['TileMapLayer', 'Tilemaps & grids'],
  ['TileMap', 'Tilemaps & grids'],
  ['VisibleOnScreenNotifier2D', 'Visibility'],
  ['VisibleOnScreenEnabler2D', 'Visibility'],
  ['Parallax2D', 'Parallax & scrolling'],
  ['ParallaxLayer', 'Parallax & scrolling'],
  ['BackBufferCopy', 'Canvas effects'],
  ['CanvasGroup', 'Canvas effects'],
  ['TouchScreenButton', 'Touch input'],
  ['Container', 'UI — containers'],
  ['Control', 'UI — controls'],
  ['MultiMeshInstance2D', '2D rendering'],
  ['MeshInstance2D', '2D rendering'],
  ['AnimatedSprite2D', '2D rendering'],
  ['Sprite2D', '2D rendering'],
  ['Polygon2D', '2D rendering'],
  ['Line2D', '2D rendering'],
  // CanvasModulate is a Node2D, so it precedes the Node2D catch-all.
  ['CanvasModulate', 'Canvas effects'],
  ['Node2D', '2D generic'],

  // Neither CanvasItem nor Node3D.
  ['CanvasLayer', 'Canvas layers'],
  ['Window', 'UI — windows'],
  ['AnimationPlayer', 'Animation'],
  ['AnimationTree', 'Animation'],
  ['AnimationMixer', 'Animation'],
  ['Tween', 'Animation'],
  ['AudioStreamPlayer', 'Audio'],
  ['Timer', 'Timers & logic'],
  ['HTTPRequest', 'Networking'],
  ['MultiplayerSpawner', 'Networking'],
  ['MultiplayerSynchronizer', 'Networking'],
  ['ResourcePreloader', 'Resources'],
  ['ShaderGlobalsOverride', 'Rendering globals'],
  ['StatusIndicator', 'OS integration'],
  ['XRServer', 'XR / AR'],
  ['SubViewport', 'Viewports'],
  ['SpringBoneCollision3D', 'Skeleton, bones & IK'],
];

export function groupOf(node) {
  const names = new Set([node.name, ...node.chain]);
  for (const [base, group] of GROUP_RULES) if (names.has(base)) return group;
  if (/^(OpenXR|XR)/.test(node.name)) return 'XR / AR';
  if (node.name.startsWith('SpringBone')) return 'Skeleton, bones & IK';
  // A base node or an unfamiliar base still gets a group by dimension.
  if (names.has('Node3D')) return '3D generic';
  if (names.has('CanvasItem')) return '2D generic';
  return 'Generic';
}
