/**
 * The `vscode` module mock, as one object: `test-setup.ts` installs it with `vi.mock`
 * and exports it as `vscode`, so a test arranges the same object the code under test
 * imports. A new VS Code API needs one entry here.
 */

import {
  mockCommands,
  mockLanguages,
  mockLm,
  mockUri,
  mockWindow,
  mockWorkspace,
} from './vscodeMocks.testkit';
import {
  MockCodeAction,
  MockCodeActionKind,
  MockCompletionItem,
  MockCompletionItemKind,
  MockCompletionItemTag,
  MockDiagnostic,
  MockDiagnosticSeverity,
  MockDocumentHighlight,
  MockDocumentHighlightKind,
  MockDocumentLink,
  MockDocumentSymbol,
  MockEventEmitter,
  MockFileType,
  MockFoldingRange,
  MockFoldingRangeKind,
  MockHover,
  MockLanguageModelDataPart,
  MockLanguageModelTextPart,
  MockLanguageModelToolResult,
  MockLocation,
  MockMarkdownString,
  MockPosition,
  MockRange,
  MockRelativePattern,
  MockSelection,
  MockSymbolKind,
  MockTabInputText,
  MockTextEditorRevealType,
  MockViewColumn,
  MockWorkspaceEdit,
} from './vscodeMockClasses.testkit';

export const vscodeModuleMock = {
  Uri: mockUri,
  workspace: mockWorkspace,
  window: mockWindow,
  commands: mockCommands,
  languages: mockLanguages,
  lm: mockLm,
  Range: MockRange,
  Position: MockPosition,
  Selection: MockSelection,
  EventEmitter: MockEventEmitter,
  DocumentSymbol: MockDocumentSymbol,
  DocumentLink: MockDocumentLink,
  Location: MockLocation,
  Diagnostic: MockDiagnostic,
  MarkdownString: MockMarkdownString,
  Hover: MockHover,
  CompletionItem: MockCompletionItem,
  CompletionItemKind: MockCompletionItemKind,
  CompletionItemTag: MockCompletionItemTag,
  CodeAction: MockCodeAction,
  CodeActionKind: MockCodeActionKind,
  WorkspaceEdit: MockWorkspaceEdit,
  FoldingRange: MockFoldingRange,
  FoldingRangeKind: MockFoldingRangeKind,
  DocumentHighlight: MockDocumentHighlight,
  DocumentHighlightKind: MockDocumentHighlightKind,
  LanguageModelTextPart: MockLanguageModelTextPart,
  LanguageModelToolResult: MockLanguageModelToolResult,
  LanguageModelDataPart: MockLanguageModelDataPart,
  DiagnosticSeverity: MockDiagnosticSeverity,
  TabInputText: MockTabInputText,
  RelativePattern: MockRelativePattern,
  ViewColumn: MockViewColumn,
  FileType: MockFileType,
  TextEditorRevealType: MockTextEditorRevealType,
  SymbolKind: MockSymbolKind,
};
