/**
 * The vendoring manifest, alone in its own file so the flow that consumes it
 * stays readable next to a list this long.
 */

/**
 * The exact source-relative paths to vendor (the res:// closure as curated at
 * the pre-strip commit). Kept verbatim so each scene's `res://…` references
 * resolve once mirrored under public/fixtures/. This is a deliberate curated
 * whitelist — never derive it by walking the source, or newly added game
 * assets would be vendored silently. To re-list the original closure:
 *   git ls-tree -r --name-only d7cc1791 scenes/ld58 | sed 's|^scenes/ld58/||'
 */
export const FILES = [
  'ClueContainer.tscn',
  'ClueItem.tscn',
  'HallwayGeometry.tscn',
  'Scenes/AboutDialog/AboutDialog.tscn',
  'Scenes/DialogSystem/DialogSystem.tscn',
  'Scenes/EndGameDialog/EndGameDialog.tscn',
  'Scenes/Evidence/DroppedLedger/DroppedLedger.glb',
  'Scenes/Evidence/DroppedLedger/DroppedLedger.tscn',
  'Scenes/Evidence/Handkerchief/Flowers1_N.jpg',
  'Scenes/Evidence/Handkerchief/Flowers1_S.jpg',
  'Scenes/Evidence/Handkerchief/Handkerchief.glb',
  'Scenes/Evidence/Handkerchief/Handkerchief.tscn',
  'Scenes/Evidence/Handkerchief/HandkerchiefModel.tscn',
  'Scenes/Evidence/LetterOpener/LetterOpener.tscn',
  'Scenes/Evidence/LetterOpener/royal-dagger.glb',
  'Scenes/GameUI/GameUI.tscn',
  'Scenes/Hallway/Hallway.tscn',
  'Scenes/PhotoFrame/Boat/Boat.tscn',
  'Scenes/PhotoFrame/Boat/boat.png',
  'Scenes/PhotoFrame/Books/Books.tscn',
  'Scenes/PhotoFrame/Books/books.png',
  'Scenes/PhotoFrame/Car/Car.tscn',
  'Scenes/PhotoFrame/Car/car.png',
  'Scenes/PhotoFrame/Cat/Cat.tscn',
  'Scenes/PhotoFrame/Cat/cat.png',
  'Scenes/PhotoFrame/Clock/Clock.tscn',
  'Scenes/PhotoFrame/Clock/clock.png',
  'Scenes/PhotoFrame/Dog/Dog.tscn',
  'Scenes/PhotoFrame/Dog/dog.png',
  'Scenes/PhotoFrame/DrHenryMorrison/DrHenryMorrison.png',
  'Scenes/PhotoFrame/DrHenryMorrison/DrHenryMorrison.tscn',
  'Scenes/PhotoFrame/EleanorHartwell/EleanorHeartwell.tscn',
  'Scenes/PhotoFrame/EleanorHartwell/Mrs. Eleanor Hartwell.png',
  'Scenes/PhotoFrame/Flowers/Flowers.tscn',
  'Scenes/PhotoFrame/Flowers/flowers.png',
  'Scenes/PhotoFrame/HouseKeeper/HouseKeeper.tscn',
  'Scenes/PhotoFrame/HouseKeeper/SarahMills.png',
  'Scenes/PhotoFrame/InspectorCrawford/InspectorCrawford.png',
  'Scenes/PhotoFrame/InspectorCrawford/InspectorCrawford.tscn',
  'Scenes/PhotoFrame/LadyBlackwood/Lady Margaret Blackwood.png',
  'Scenes/PhotoFrame/LadyBlackwood/LadyBlackwood.tscn',
  'Scenes/PhotoFrame/YoungTimBlackwood/Young Timothy Blackwood.png',
  'Scenes/PhotoFrame/YoungTimBlackwood/YoungTimBlackwood.tscn',
  'Scenes/StartScreen/StartScreen.tscn',
  'assets/PortraitFrame2.glb',
  'assets/doormesh.glb',
  'assets/doormesh.tscn',
  'assets/entrance_door_material.tres',
  'assets/grandfatherclock.glb',
  'assets/grandfatherclock.tscn',
  'assets/interior_door_material.tres',
  'assets/picture_frames_lib/picture_frame_victorian_1.glb',
  'assets/picture_frames_lib/picture_frame_victorian_2.glb',
  'assets/picture_frames_lib/picture_frame_victorian_3.glb',
  'assets/picture_frames_lib/picture_frame_victorian_5.glb',
  'assets/picture_frames_lib/textures/picture_frames_dif.png',
  'assets/picture_frames_lib/textures/picture_frames_nor.png',
  'assets/picture_frames_lib/victorian_1.tscn',
  'assets/picture_frames_lib/victorian_2.tscn',
  'assets/picture_frames_lib/victorian_3.tscn',
  'assets/picture_frames_lib/victorian_5.tscn',
  'assets/roof_lamp.glb',
  'assets/roof_lamp.png',
  'assets/roof_lamp.tscn',
  'assets/textures/WhiteRaised_N.jpg',
  'assets/textures/WhiteRaised_S.jpg',
  'assets/textures/fy_acc_lien.png',
  'assets/textures/g_toit-tower.png',
  'assets/textures/wood tex1.png',
  'assets/textures/wood tex2.png',
  'assets/textures/wood1.png',
  'components/CornerColumn.tscn',
  'components/Door.tscn',
  'components/EntranceDoor.tscn',
  'components/InteractableObject.tscn',
  'components/WallSection.tscn',
  'main.tscn',
  'shaders/pixel_perfect_ouline.tres',
  'shaders/pixel_perfect_outline.gdshader',
];
